Feature
SasaDjikic/cat-api pull request #2
Opened 2024-09-27 09:32 UTC by SasaDjikic

2024-09-27 11:55 UTC, FloEberle requested changes
paar generelle feedbacks. bis am montag :)

2024-09-27 11:55 UTC, FloEberle commented on src/main/java/ch/cat_api/catapi/handlers/exceptions/ExceptionHandler.java
> +public class ExceptionHandler implements Handler<RoutingContext>
der handler sollte gemäss api docs json retournieren, keinen plain text

2024-09-27 11:55 UTC, FloEberle commented on src/main/java/ch/cat_api/catapi/MainVerticle.java
> +      .onSuccess(res -> System.out.println("MainVerticle successfully deployed"))
die ganze system.out.println wären doch optimal für den logger (im ganzen projekt, ich scheibs nicht mehr hin)

2024-09-27 11:55 UTC, FloEberle commented on src/main/java/ch/cat_api/catapi/verticles/CatVerticle.java
> +        HttpServer server = vertx.createHttpServer().requestHandler(routerBuilder.createRouter());
genereller codestil: versuch doch wenn immer möglich variablen und properties `final` zu deklarieren. Hilft dem Compiler und dem Entwickler der den Code liest.

Mehr zum lesen: https://www.baeldung.com/java-final-performance

2024-09-27 11:55 UTC, FloEberle commented on src/test/java/ch/cat_api/catapi/repositories/CatRepositoryTest.java
> +  public void testLoadReturnsResultOfCatRepository()
ich empfehle dir noch das `SonarLint` Plugin zu installieren, das hat viele nützliche Inspections und Warnings, wie zum Beispiel hier, warum das `public` nicht nötig ist.

<img width="2326" alt="image" src="https://github.com/user-attachments/assets/2c007d74-fb8f-44cc-8a68-d67cb2ebf6ea">

2024-09-27 11:55 UTC, FloEberle commented on src/test/java/ch/cat_api/catapi/repositories/CatRepositoryTest.java
> +  public void testLoadOfCatRepositoryFails()
hier habe ich mich gefragt, ob das verhalten überhaupt sinn macht. warum gibt der entpunkt nicht einfach eine leere liste zurück?

auch ist das verhalten 404/NotFoundException im openapi so gar nicht spezifiziert

<img width="692" alt="image" src="https://github.com/user-attachments/assets/09a1e9ef-8c2c-4a0d-8808-0e4734ef0df3">

2024-09-27 11:55 UTC, FloEberle commented on src/test/java/ch/cat_api/catapi/repositories/CatRepositoryTest.java
> +    assertInstanceOf(NotFoundException.class, future.cause());
hier könnte man noch die exception zusichern nicht nur den typ der exception

2024-09-27 11:55 UTC, FloEberle commented on src/main/java/ch/cat_api/catapi/verticles/CatVerticle.java
> +        throw new RuntimeException("Router builder failed to created");
hier verschluckst du komplett die root cause (`err`) und evtl wäre hier logging angebracht, wdyt?

2024-09-27 11:55 UTC, FloEberle commented on src/main/java/ch/cat_api/catapi/util/CatMapper.java
> +      final ObjectMapper objectMapper = new ObjectMapper();
der ObjectMapper ist einer dependency vom CatMapper und kommt als dependency in deine Klasse, das dürfte dir auch das Tests schreiben einfacher machen.

2024-09-30 08:24 UTC, SasaDjikic commented on src/test/java/ch/cat_api/catapi/repositories/CatRepositoryTest.java
> +    assertInstanceOf(NotFoundException.class, future.cause());
Verstehe nicht ganz, was mit zusichern gemeint ist. AssertThrow funktioniert nicht.

2024-10-02 14:59 UTC, FloEberle approved these changes
sieht gut aus, glaub du hast es verstanden 🤩 

-> schau dir mal karate tests an als nächstes, dann versuchen wir noch die äusserste schicht vom testing anzuschauen und dann sind wir durch mit dem thema denke ich.

2024-10-02 14:59 UTC, FloEberle commented on src/main/java/ch/cat_api/catapi/handlers/get/CatGetHandler.java
> +        routingContext.response().end();
ich glaube die zeile `routingContext.response().end()` ist nicht nötig. betrifft alle handler die .json aufrufen, das beendet den request.

2024-10-23 11:08 UTC, merged